INSERT INTO "SYS_USER" ("USER_ID","USER_NAME","PASSWORD","REAL_NAME","STATUS","CREATE_CODE","CREATE_DATE","UPDATE_CODE","UPDATE_DATE")
SELECT 'user-test01', 'test', '0192023a7bbd73250516f069df18b500', '测试用户', '1', 'admin', NOW(), 'admin', NOW()
WHERE NOT EXISTS (SELECT 1 FROM "SYS_USER" WHERE "USER_NAME"='test');
